### ISSUE TITLE
Resubscribing after client reconnects?

### ISSUE THREAD

**Issue by jvii** [bitrich-info/xchange-stream#15]
I have been streaming tickers from Poloniex succesfully by following the example [here](https://github.com/bitrich-info/xchange-stream/blob/develop/xchange-poloniex/src/test/java/info/bitrich/xchangestream/poloniex/PoloniexManualExample.java). Works nicely, but everytime the wampclient disconnects (and automatically reconnects) I lose all my subscribtions. So I guess I should always resubscribe to getTicker when the client state changes to connected, but what is the best way to detect this? I can only see the "State changed:" log message when this happens.

Very new to RxJava, so the answer might be obvious, but I just can't seem to figure it out. Thanks!

**Comment by dozd** [comment]
Hmm that's quite tricky and probably can't be accomplished right now.

Connect() probably need to be changed to Observable and cannot be Completed upon connection like now. Then it should be possible to listen for connection events in subscribe of connect() and resolve them.

It's pretty big change, I forgot this scenario when designing the library.

**Comment by dozd** [comment]
Maybe, it could be possible to make automatic resubscriptions for wamp only.

**Comment by dozd** [comment]
It's also a little connected to the WAMP library I'm using. I've increased the version of jawampa-netty in latest release (2.3.0). Just try it again to be sure, issue is still here.

**Comment by roeiba** [comment]
With regards to poloniex, There are two exchanges:
1. xchange-poloniex2 (using Netty)
2. xchange-poloniex (using WAMP)

Which project is the recommended?

**Comment by dozd** [comment]
I suppose newer which is poloniex2

**Comment by firegnome** [comment]
@roeiba poloniex2 is using the websocket from the poloniex webpage and was implemented because the WAMP socket is lagging several hours behind, i strongly suggest poloniex2 if you need live data.

This is a problem I recognized too and we really need a solution for this. For a first workaround i would suggest to provide a callback if the websocket is closing. With such a solution we would have the ability to reconnect manually.

**Comment by dozd** [comment]
@firegnome I'm not aware of this problem on other exchanges but I think it could happen there as well. I think solution is either change method `connect` from `Completable` to `Observable` and have connection events to be observed or implement some kind of internal auto re-subscribing feature in all implementation services.

**Comment by firegnome** [comment]
I implemented a re-subscribe feature in **NettyStreamingService**. Additionally I did override the WebSocketClientHandler in poloniex2 to get the disconnect event. I'm currently testing if this is actually working... its a little bit odd because i have to wait for the websocket to close -.-

I'm looking forward to your feedback https://github.com/firegnome/xchange-stream/commit/efff9ddbb204d3c9f3a66253eac6075328107636

**Comment by firegnome** [comment]
I tested it and the reconnect is working.  
![image](https://user-images.githubusercontent.com/3715918/33762028-62206092-dc0b-11e7-92c5-55c95ea2e51e.png)

**Comment by jvii** [comment]
Looks good, thanks for this! As the old wamp api had become almost unusable and xchange-poloniex2 didn't exist yet back in september, I ended up implementing a simple streamer for api2 using Tyrus (which supports reconnects). It works pretty nicely, but I might give this a try later too.
