### ISSUE TITLE
BitMEX: Error parsing incoming message to JSON

### ISSUE THREAD

**Issue by somguyth** [bitrich-info/xchange-stream#170]
Is anyone else getting a spam of these log messages when trying to receive BitMEX data? I've been getting this since about 30 mins ago, tried reconnecting/restarting multiple times but no luck.

ERROR  [JsonNettyStreamingService] Error parsing incoming message to JSON: B���|��

**Comment by hlbkin** [comment]
Same thing. This is probably because theyve added compression. Need to find out way to add compression somewhere....

**Comment by somguyth** [comment]
@hlbkin  Where does it say they've added compression?

**Comment by hlbkin** [comment]
@somguyth 
I just know it because I watched messages coming in debug mode. It happened with a couple of exchanges in last couple of month and same thing.

Also I've just fixed everything

You need to override method in BitmexStreamingService and create your custom handler for compression

@ChannelHandler.Sharable
public final class BitmexWebsocketHandler extends WebSocketClientExtensionHandler {

    public static final BitmexWebsocketHandler INSTANCE = new BitmexWebsocketHandler();

    private BitmexWebsocketHandler() {
        super(new DeflateFrameClientExtensionHandshaker(false),
                new DeflateFrameClientExtensionHandshaker(true));
    }

}

    @Override
    protected WebSocketClientExtensionHandler getWebSocketClientExtensionHandler() {
        return BitmexWebsocketHandler.INSTANCE;
    }

**Comment by somguyth** [comment]
@hlbkin 

Thanks, but I'm not sure what you mean by "I deleted new PerMessageDeflateClientExtensionHandshaker() from here"?

I did a grep search of the string "new PerMessageDeflateClientExtensionHandshaker()" and could only find such a usage in the gdax library, but no such reference in the bitmex library.

**Comment by hlbkin** [comment]
This is in NettyStreamingService

**Comment by somguyth** [comment]
@hlbkin 

I can confirm this fixes the problem. Thank you very much.
