### ISSUE TITLE
Help with xchange-stream maintenance

### ISSUE THREAD

**Issue by nikolaenkov** [bitrich-info/xchange-stream#181]
Hi, @dozd could not find any other way to direct message you. 

Feel free to contact me if you need help with maintenance. We had to copy xchange-stream repo locally and significantly patched/changed it to make more stable (and sometimes to make it work :)) At that time it was easier/faster for us. Now we're thinking of giving back our work to the community.

Thanks for your effort.

**Comment by jkolobok** [comment]
Same here.

**Comment by badgerwithagun** [comment]
Potentially also willing to assist.

Has there been any dialogue with the Xstream maintainer(s)? Having these two as separate projects will always mean this one will be constantly struggling to keep up.

**Comment by dozd** [comment]
Hello, sorry for the late response. I'm happy you want to help with the maintenance of the project. As I really don't know how to check the quality of your potential contribution I'd like you to make review of each others (or any other) PR for this time. If you approve PR (not yours) I have no problem with the merge.
I think you can assign yourself as a reviewer for any PR, so feel free to pick any and approve / comment it. I added you as contributors (with the read access only for now). Also, submit yours PR if you haven't done it yet, 

When I started the project I have only one goal: the simplicity for the end user. So have this also in your mind :).

@badgerwithagun About the Xchange integration: There was streaming support for some exchanges in the Xchange library itself but because of the bad implementation they found it hard to maintain and remove it. I think a separate library works very well and it's really not hard to be up to date with the latest release version of the Xchange. Even there can be a branch that is "prepared" for the upcoming Xchange release and it can depend on the snapshot version of the Xchange.

**Comment by jkolobok** [comment]
Only contributors with write access can approve PRs. Others can just comment. There are some of PRs with comments. 
e,g my PR here (unfortunately several fixes in one PR ) https://github.com/bitrich-info/xchange-stream/pull/185 

PRs with comments:)
https://github.com/bitrich-info/xchange-stream/pull/188
https://github.com/bitrich-info/xchange-stream/pull/191

**Comment by dozd** [comment]
@jkolobok I think that when you assign yourself as an review and click start the review, then you can then submit review as Approve or Changes requested. So if you are fine and approve the PR without any requested changes, all checks will be passed I just click (for now) the merge button.

**Comment by jkolobok** [comment]
I added reviews https://github.com/bitrich-info/xchange-stream/pull/188#pullrequestreview-127405513

**Comment by jkolobok** [comment]
Any updates? Or the project can be considered dead?

**Comment by dozd** [comment]
No response from anyone else 👎, nor on your requested changes in the review. Not dead, but I cannot find spare time now.

**Comment by jkolobok** [comment]
I can verify and merge changes if you want. Everyone is doing it in their own repo and everyone gets out of sync (we are doing it in our own - https://github.com/KapitalTrading/xchange-stream). The project dies...

**Comment by dozd** [comment]
Sure you can, just mark the changes that are good to merge with positive review. That's all :-).

**Comment by badgerwithagun** [comment]
I've added reviews with suggested changes, but they're still marked as "awaiting review" (even though I've added a review) and there's been no follow-up from the contributors.

I'd just fix up the code and merge it if I could.

**Comment by dozd** [comment]
@badgerwithagun link to the PR you have tried to merge

**Comment by badgerwithagun** [comment]
#160. All I wanted to do was to merge `develop` into the PR's branch to resolve the conflicts.

**Comment by dozd** [comment]
#224
