### ISSUE TITLE
bitfinex order book: BTC/USDT not valid pair

### ISSUE THREAD

**Issue by firepol** [bitrich-info/xchange-stream#265]
Hi,

in other libraries I'm using (e.g. ccxt) the pair used to query the exchange must match the exchange.

E.g. binance I subscribe to the order book using: BTC/USDT

On bitfinex if I use BTC/USDT I get invalid pair. This is strange, because this is actually the correct pair.
If I use BTC/USD it works.

I find it inconsistent (looks like a bug to me). Thoughts?

**Comment by badgerwithagun** [comment]
Not checked, but bitfinex might be one of the exchanges that uses a coin list in the bitfinex.json file, rather than fetching it at runtime from the exchange. If so, we pick up the updated bitfinex.json file when we update our XChange dependency. Currently we are a few versions behind. Since this pair only launched recently, it may be updated in XChange 4.3.13 or might not have been updated yet at all.

I have opened #261 to upgrade us to the latest version of XChange, which might help.

As a workaround, you can supply a modified bitfinex.json file in the `ExchangeSpecification` when you connect. Just copy the one from XChange's code, add the pair and pass the path to it when you connect.

**Comment by kroitor** [comment]
@firepol https://github.com/ccxt/ccxt/issues/4285

**Comment by badgerwithagun** [comment]
Closing as stale. Please re-open if this is still an issue.
