### ISSUE TITLE
Replacing Observable<UserTrade> method to Observable<UserTrades> on StreamingTradeServivce

### ISSUE THREAD

**Issue by makarid** [bitrich-info/xchange-stream#388]
Hello, i would like to ask everyone if it is ok to change the method in StreamingTradeService in order to send a list of UserTrades instead of a single UserTrade. Many exchanges send a list of usertrades instead of just one trade. I am waiting for your response.Thanks

**Comment by badgerwithagun** [comment]
Can't you just use `flatMap` to flatten out the list?

**Comment by badgerwithagun** [comment]
https://stackoverflow.com/questions/29672705/convert-observablelistcar-to-a-sequence-of-observablecar-in-rxjava

**Comment by makarid** [comment]
We need to do that to every exchange implementation then.

**Comment by makarid** [comment]
For example, the implementation that there is in Coinbase Pro right now, will give only the first trade of the list. If there will be more that 1 trades simultaneously then only the first one will be send to the consumer.

**Comment by badgerwithagun** [comment]
> We need to do that to every exchange implementation then.

I'm not aware of any, Could you point to one? This API is intended to return trades as they occur. I can't think of any good reason why an exchange would return more than one trade in a single Websocket message unless it was sending a snapshot of all previous trades, but all exchanges I've seen expect you to use the REST APIs for that.

Are you possibly trying to implement this API using REST APIs?  XChange already has `TradeService` for that. As discussed at the time this API was implemented, we decided against trying to implement these APIs for exchanges which lack the websocket support. Instead, application code should fall back gracefully to `TradeService` if it gets `NotImplementedForExchangeException` when trying `StreamingTradeService`.

**Comment by badgerwithagun** [comment]
> For example, the implementation that there is in Coinbase Pro right now, will give only the first trade of the list. If there will be more that 1 trades simultaneously then only the first one will be send to the consumer.

That's not how the `flatMap` operation works.  It takes a stream of `List<UserTrade>` and expands that into a stream of `UserTrade` containing all the `UserTrades` from all of the lists.

**Comment by makarid** [comment]
For example the Coinmate Exchange sends a list of usertrades on their websocket API. Also on the CoinbasePro implementation, as i see it the adaptHistory method returns a UserTrades object instead of UserTrade.

**Comment by makarid** [comment]
Anyway, using concatMapIterable fixes the problem with lists.

**Comment by makarid** [comment]
I can just add a new endpoint like Observable<UserTrades> getUserTrades in order to have both endpoints and choose the one that anyone wants.

**Comment by badgerwithagun** [comment]
I've [already implemented](https://github.com/gruelbox/orko/blob/master/orko-common/src/main/java/com/gruelbox/orko/marketdata/MarketDataSubscriptionManager.java) such an adapter.  The thing is, it's a bit more complex than just using REST for some exchanges and not others.

Remember, websockets are not a reliable source of trade updates unless the web socket provides a self-correction mechanism (most exchanges don't).  Websockets can disconnect and reconnect and your application (and Netty) won't know.  As a result, websockets are very likely to miss updates and you will not be given any warning that this has happened.  The only safe way to keep the open orders up-to-date is to poll the REST endpoint.  All the websocket can do is to make your updates more frequent (so poll the REST endpoint every 30 seconds, say, and take websocket updates to get more responsive updates between the polls).

So, what I do is do both, and merge them into a single `Observable<UserTrade>` using an intermediary service, so that my code _only_ has to listen to a single stream for all exchanges. You're welcome to [copy my code](https://github.com/gruelbox/orko/blob/master/orko-common/src/main/java/com/gruelbox/orko/marketdata/MarketDataSubscriptionManager.java).

Hopefully it's obvious why this would be more complex if some exchanges implemented `Observable<UserTrade> getUserTrades` and some implemented `Observable<List<UserTrade>>` - it's much easier to collapse everything down to just `UserTrade` than it is to deal with two different APIs.

**Comment by makarid** [comment]
Thanks a lot for your input @badgerwithagun! I have fix the problem with websockets reconnection on orderbook by adding a timeout(30 sec) followed by a retry() on the stream chain. The same cannot be done on UserTrades unfortunately. I have also created one websocket and REST connector for userTrades but i have made it to return Observable<UserTrades> instead of Observable<UserTrade> :). I will check your code in order to see how you have convert the REST API UserTrades getTradeHistory(TradeHistoryParams params) endpoint to return Observable<UserTrade>. After that i believe that i will not have any issue to use Observable<UserTrade>. Thanks

**Comment by badgerwithagun** [comment]
In short - I poll and push the results into a `Subject` along with the data from the websocket :)
