### ISSUE TITLE
Can i become a maintainer in order to help merge updates quicker?

### ISSUE THREAD

**Issue by makarid** [bitrich-info/xchange-stream#389]

**Comment by makarid** [comment]
@badgerwithagun @dozd is it possible to add me as maintainer in order to check at least for the minor updates and merge them quicker?

**Comment by badgerwithagun** [comment]
Hi @makarid.

Thanks loads for offering.

I've had a chat with @dozd.  We desperately do need more maintainers, but in this case, we need some more examples of your work before @dozd can give you merge rights.

I know it's frustrating getting PR merges delayed, but you'll notice that mostly, the simple ones which clearly solve a specific problem _do_ get reviewed (relatively) quickly. #316  and #362, though, contained good work, but they were big "catch all" merges, which are hard to review and approve, which is why they ended up getting re-worked by others before being merged.

Send through some clean, compact PRs, then (a) you will notice they get merged much quicker and (b) it'll give a good impression that you should get merge access.

**Comment by dozd** [comment]
Very well written.

**Comment by makarid** [comment]
Thanks a lot both of you for the reply and suggestion! I need to learn more about github then. Don't worry one day i will be fit for merge access :)
