### ISSUE TITLE
Problem with orderbook BTC-EUR  of CoinbasePro

### ISSUE THREAD

**Issue by GiuseppeLantieri** [bitrich-info/xchange-stream#403]
Hi Everybody I noticed an error with the WS of CoinbasePro, when i subscribe on channel to get OrderBook of BTC - EUR i receive the correct data only for two seconds.
Someone have the same problem?

**Comment by makarid** [comment]
I had the same issue. The fix is this: 
Well i just found the CoinbasePro issue which didn't delete the zero volume values. On the CoinbaseProWebsocketTransaction.CoinbaseProOrderbookChanges, in the line 138 we must change the way we check the volume !=0. Right now we check if !(String)volume.equals("0") which is not correct. We must change it to Double.parseDouble(volume) != 0.0 . I will implement it

**Comment by badgerwithagun** [comment]
I believe this is now fixed. Closing unless anyone knows any different.
