### ISSUE TITLE
[question] General - are there only new or also removed orders in the stream?

### ISSUE THREAD

**Issue by archenroot** [bitrich-info/xchange-stream#55]
As questions says, imagine I have complete map of orders and what is exactly coming in via stream, only added or also removed orders from exchange?

Thanks a lot anyway for this cool extension.

**Comment by dozd** [comment]
I think it depends on the exchange implementation and the data type of the order book. But generally there are lists of active orders (like live mirror of the order book).

**Comment by archenroot** [comment]
Maybe just to explain, so this library actually is doing background pooling continuously for all orders, or it is provided by external exchange APIs? 

I mean, if the stream is constructed from continuous queries (not provided natively by API of exchange), maybe I can get better performance (and up-to-date) data by doing query from let's say 5 independent hosts, first at each 0ms, second at 200ms, etc.. or is my thinking irrelevant (regarding this communication schema which xchange-stream provides?

**Comment by dozd** [comment]
Nope the library is based on websocket protocol so exchange must support stream API for consistent stream of data (which should be faster & reliable than polling through REST). There will be latency but smaller because http connection is kept open for whole session.

So this library is just creating cool consistent java API for all exchanges so you don't need to mess around with websocket protocol by yourself.

**Comment by archenroot** [comment]
That is really cool!!!
